version: "3"
services:
  erp-nginx:
    image: nginx
    container_name: erp-nginx
    restart: always
    volumes:
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-conf/localhost.crt:/etc/ssl/localhost.crt
      - ./nginx-conf/localhost.key:/etc/ssl/localhost.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - erp-odoo

  erp-odoo:
    image: odoo:13.0
    container_name: erp-odoo
    restart: always
    depends_on:
      - erp-postgres
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - ./custom-addons:/mnt/extra-addons
      - ./odoo-conf:/etc/odoo

  erp-postgres:
    image: postgres:latest
    container_name: erp-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - erp-pgdata:/var/lib/postgresql/data

volumes:
  erp-pgdata:
