version: '3'
services:
  sso-nginx:
    image: nginx
    container_name: sso-nginx
    restart: on-failure
    volumes:
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-conf/localhost.crt:/etc/ssl/localhost.crt
      - ./nginx-conf/localhost.key:/etc/ssl/localhost.key
    ports:
      - "80:80"
      - "443:443"
    networks:
      sso-network:
        ipv4_address: 172.13.13.13

  sso-keycloak:
    build: .
    container_name: sso-keycloak
    restart: on-failure
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=postgres
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_ADDR=sso-postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloakdb
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - "8080:8080"      
    depends_on:
      - sso-postgres
    networks:
      sso-network:
        ipv4_address: 172.13.13.14

  sso-postgres:
    image: postgres
    container_name: sso-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloakdb
    volumes:
      - sso-pgdata:/var/lib/postgresql/data
    networks:
      sso-network:
        ipv4_address: 172.13.13.15


volumes:
  sso-pgdata:

networks:
  sso-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.13.0.0/16